using System;
using System.Drawing;
using System.Windows.Forms;

namespace PremiumLivingFurnitureWinForms;

public class RawMaterialRequestForm : UserControl
{
    readonly TextBox search = new() { Width = 320 };
    readonly DataGridView grid = new();
    public RawMaterialRequestForm() { Dock = DockStyle.Fill; BackColor = Theme.Bg; Build(); LoadData(); }
    void Build() { var root = new TableLayoutPanel { Dock = DockStyle.Fill, RowCount = 3, ColumnCount = 1, Padding = new Padding(30), BackColor = Theme.Bg }; root.RowStyles.Add(new RowStyle(SizeType.Absolute, 84)); root.RowStyles.Add(new RowStyle(SizeType.Absolute, 76)); root.RowStyles.Add(new RowStyle(SizeType.Percent, 100)); root.Controls.Add(new Label { Text = "Raw Material Requests\r\nProduction Processing Management: Add, Edit, Search and Track Raw Material Requests", Dock = DockStyle.Fill, Font = new Font("Segoe UI", 18, FontStyle.Bold), ForeColor = Theme.Text, BackColor = Theme.Bg }, 0, 0); var bar = new FlowLayoutPanel { Dock = DockStyle.Fill, BackColor = Color.White, Padding = new Padding(12), WrapContents = false }; bar.Controls.Add(new Label { Text = "Search", AutoSize = true, Padding = new Padding(0, 10, 5, 0), BackColor = Color.White, ForeColor = Theme.Muted, Font = new Font("Segoe UI", 9, FontStyle.Bold) }); search.Margin = new Padding(0, 6, 16, 6); search.TextChanged += (_, _) => LoadData(); bar.Controls.Add(search); var add = Theme.PrimaryButton("Add New", 115); var edit = Theme.SecondaryButton("Modify Row", 125); var delete = Theme.SecondaryButton("Delete", 100); var refresh = Theme.SecondaryButton("Refresh", 105); add.Click += (_, _) => AddNew(); edit.Click += (_, _) => EditSelected(); delete.Click += (_, _) => DeleteSelected(); refresh.Click += (_, _) => LoadData(); bar.Controls.Add(add); bar.Controls.Add(edit); bar.Controls.Add(delete); bar.Controls.Add(refresh); root.Controls.Add(bar, 0, 1); Theme.Grid(grid); grid.CellDoubleClick += (_, e) => { if (e.RowIndex >= 0) EditSelected(); }; root.Controls.Add(grid, 0, 2); Controls.Add(root); }
    void LoadData() { try { grid.DataSource = Database.RawRequests(search.Text.Trim()); HideTechnicalColumns(); } catch (Exception ex) { MessageBox.Show(ex.Message, "Raw Material Requests"); } }
    void HideTechnicalColumns() { foreach (string col in new[] { "StockId", "RequestedByUserId" }) if (grid.Columns.Contains(col)) grid.Columns[col].Visible = false; if (grid.Columns.Contains("RequestedBy")) grid.Columns["RequestedBy"].HeaderText = "Requested By"; if (grid.Columns.Contains("ItemCode")) grid.Columns["ItemCode"].HeaderText = "Stock Code"; if (grid.Columns.Contains("ItemName")) grid.Columns["ItemName"].HeaderText = "Stock Item"; if (grid.Columns.Contains("RequiredDate")) grid.Columns["RequiredDate"].HeaderText = "Required Date"; if (grid.Columns.Contains("CreatedDate")) grid.Columns["CreatedDate"].HeaderText = "Created Date"; grid.ClearSelection(); }
    void AddNew() { using var form = new RawMaterialRequestEditForm(); if (form.ShowDialog(FindForm()) != DialogResult.OK) return; Database.AddRawRequest(form.StockId, form.RequestedByUserId, form.Quantity, form.RequiredDate, form.Priority, form.Status, form.Purpose); LoadData(); }
    void EditSelected() { if (grid.CurrentRow == null || !grid.Columns.Contains("Id")) { MessageBox.Show("Please select one raw material request first.", "Modify Row"); return; } using var form = new RawMaterialRequestEditForm(grid.CurrentRow); if (form.ShowDialog(FindForm()) != DialogResult.OK) return; Database.UpdateRawRequest(form.RequestId, form.StockId, form.RequestedByUserId, form.Quantity, form.RequiredDate, form.Priority, form.Status, form.Purpose); LoadData(); }
    void DeleteSelected() { if (grid.CurrentRow == null || !grid.Columns.Contains("Id")) return; int id = Convert.ToInt32(grid.CurrentRow.Cells["Id"].Value); if (MessageBox.Show("Delete selected raw material request?", "Confirm Delete", MessageBoxButtons.YesNo, MessageBoxIcon.Question) != DialogResult.Yes) return; Database.DeleteRecord("RawMaterialRequests", id); LoadData(); }
}

public class RawMaterialRequestEditForm : Form
{
    readonly TextBox requestNo = new() { ReadOnly = true }; readonly ComboBox stock = new() { DropDownStyle = ComboBoxStyle.DropDownList }; readonly ComboBox requestedBy = new() { DropDownStyle = ComboBoxStyle.DropDownList }; readonly NumericUpDown quantity = new() { Minimum = 1, Maximum = 999999, Value = 1 }; readonly DateTimePicker requiredDate = new() { Format = DateTimePickerFormat.Short, Value = DateTime.Today.AddDays(7) }; readonly ComboBox priority = new() { DropDownStyle = ComboBoxStyle.DropDownList }; readonly ComboBox status = new() { DropDownStyle = ComboBoxStyle.DropDownList }; readonly TextBox purpose = new() { Multiline = true, ScrollBars = ScrollBars.Vertical };
    public int RequestId { get; private set; }
    public int StockId => stock.SelectedItem is LookupItem s ? s.Id : 0; public int RequestedByUserId => requestedBy.SelectedItem is LookupItem u ? u.Id : 0; public int Quantity => (int)quantity.Value; public string RequiredDate => requiredDate.Value.ToString("yyyy-MM-dd"); public string Priority => priority.Text; public string Status => status.Text; public string Purpose => string.IsNullOrWhiteSpace(purpose.Text) ? "Production raw material request" : purpose.Text.Trim();
    public RawMaterialRequestEditForm(DataGridViewRow? row = null) { RequestId = row == null ? 0 : Convert.ToInt32(row.Cells["Id"].Value); Text = RequestId == 0 ? "Add Raw Material Request" : "Modify Raw Material Request"; StartPosition = FormStartPosition.CenterParent; Size = new Size(850, 650); MinimumSize = new Size(780, 610); Font = Theme.DefaultFont; BackColor = Theme.AppBg; Build(); LoadLookups(); if (row == null) LoadNewDefaults(); else LoadExisting(row); }
    void Build() { var root = new TableLayoutPanel { Dock = DockStyle.Fill, ColumnCount = 2, Padding = new Padding(26), AutoScroll = true, BackColor = Theme.AppBg }; root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 230)); root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100)); AddRow(root, "Request No", requestNo); AddRow(root, "Stock Item", stock); AddRow(root, "Requested By", requestedBy); AddRow(root, "Quantity *", quantity); AddRow(root, "Required Date", requiredDate); AddRow(root, "Priority", priority); AddRow(root, "Status", status); int pr = root.RowCount++; root.RowStyles.Add(new RowStyle(SizeType.Absolute, 120)); root.Controls.Add(new Label { Text = "Purpose *", Dock = DockStyle.Fill, TextAlign = ContentAlignment.MiddleLeft, ForeColor = Theme.Muted, Font = new Font("Segoe UI", 9, FontStyle.Bold) }, 0, pr); purpose.Dock = DockStyle.Fill; purpose.Margin = new Padding(0, 8, 0, 8); root.Controls.Add(purpose, 1, pr); var buttons = new FlowLayoutPanel { Dock = DockStyle.Fill, FlowDirection = FlowDirection.RightToLeft, BackColor = Theme.AppBg }; var save = Theme.PrimaryButton(RequestId == 0 ? "Create Request" : "Save Changes", 145); var cancel = Theme.SecondaryButton("Cancel", 110); save.Click += (_, _) => Save(); cancel.Click += (_, _) => DialogResult = DialogResult.Cancel; buttons.Controls.Add(save); buttons.Controls.Add(cancel); int br = root.RowCount++; root.RowStyles.Add(new RowStyle(SizeType.Absolute, 62)); root.SetColumnSpan(buttons, 2); root.Controls.Add(buttons, 0, br); Controls.Add(root); }
    static void AddRow(TableLayoutPanel root, string label, Control input) { int row = root.RowCount++; root.RowStyles.Add(new RowStyle(SizeType.Absolute, 58)); root.Controls.Add(new Label { Text = label, Dock = DockStyle.Fill, TextAlign = ContentAlignment.MiddleLeft, ForeColor = Theme.Muted, Font = new Font("Segoe UI", 9, FontStyle.Bold) }, 0, row); input.Dock = DockStyle.Fill; input.Margin = new Padding(0, 8, 0, 8); root.Controls.Add(input, 1, row); }
    void LoadLookups() { stock.Items.Clear(); stock.Items.Add(new LookupItem(0, "0 - No stock item selected")); foreach (var item in Database.GetLookup("Stock")) stock.Items.Add(item); stock.SelectedIndex = 0; requestedBy.Items.Clear(); requestedBy.Items.Add(new LookupItem(0, "0 - No user selected")); foreach (var item in Database.GetLookup("Users")) requestedBy.Items.Add(item); requestedBy.SelectedIndex = 0; priority.Items.AddRange(new object[] { "Low", "Normal", "High", "Urgent" }); status.Items.AddRange(new object[] { "Submitted", "Approved", "Processing", "Issued", "Rejected", "Closed" }); priority.SelectedIndex = 1; status.SelectedIndex = 0; }
    void LoadNewDefaults() { Database.EnsureRawMaterialRequestsTable(); requestNo.Text = Database.GenerateNextCode("RawMaterialRequests", "RequestNo", "RMR", "-", 4); purpose.Text = "Production raw material request"; }
    void LoadExisting(DataGridViewRow row) { requestNo.Text = Cell(row, "RequestNo"); purpose.Text = Cell(row, "Purpose"); if (int.TryParse(Cell(row, "Quantity"), out int q) && q >= quantity.Minimum && q <= quantity.Maximum) quantity.Value = q; if (DateTime.TryParse(Cell(row, "RequiredDate"), out DateTime d)) requiredDate.Value = d; SelectLookup(stock, Cell(row, "StockId")); SelectLookup(requestedBy, Cell(row, "RequestedByUserId")); SelectText(priority, Cell(row, "Priority")); SelectText(status, Cell(row, "Status")); }
    void Save() { if (quantity.Value <= 0) { MessageBox.Show("Quantity must be greater than zero."); return; } if (string.IsNullOrWhiteSpace(purpose.Text)) { MessageBox.Show("Please enter purpose."); return; } DialogResult = DialogResult.OK; }
    static string Cell(DataGridViewRow row, string column) { if (!row.DataGridView.Columns.Contains(column)) return ""; object? value = row.Cells[column].Value; return value == null || value == DBNull.Value ? "" : Convert.ToString(value) ?? ""; }
    static void SelectLookup(ComboBox combo, string idText) { if (!int.TryParse(idText, out int id)) return; for (int i = 0; i < combo.Items.Count; i++) if (combo.Items[i] is LookupItem item && item.Id == id) { combo.SelectedIndex = i; return; } }
    static void SelectText(ComboBox combo, string text) { if (string.IsNullOrWhiteSpace(text)) return; for (int i = 0; i < combo.Items.Count; i++) if (string.Equals(Convert.ToString(combo.Items[i]), text, StringComparison.OrdinalIgnoreCase)) { combo.SelectedIndex = i; return; } }
}
